const ACTIONS = {
  SET_FOLLOWING: 'SET_FOLLOWING',
  ADD_FOLLOWING: 'ADD_FOLLOWING',
  REMOVE_FOLLOWING: 'REMOVE_FOLLOWING',
  SET_FOLLOW: 'SET_FOLLOW',
  ADD_FOLLOW: 'ADD_FOLLOW',
  REMOVE_FOLLOW: 'REMOVE_FOLLOW'
}

export default ACTIONS
